### ISSUE TITLE
Update source file for countries

### ISSUE THREAD

**Issue by bbombachini** [writecrow/country_code_converter#2]
Hello,

Thanks for this library, quite handy for what I need I just noticed some issues with the data/countries.csv file.
I was wondering if there's a better way of keeping this up to date, like potentially pulling from google API or something like that but for the time being I think it needs a patch.

For example, "Macedonia" was not returning any results mainly because the country's name in the CSV was missing quotes.

Also, Kosovo, Bonaire and Curaçao are independent countries.

Please review attachment.
[country_patch.patch](https://github.com/writecrow/country_code_converter/files/12423605/country_patch.patch)

**Comment by markfullmer** [comment]
Thanks! For the time being, I'll just update the list per the patch, which looks good.
